import Head from 'next/head'
import styles from '../styles/Home.module.css'

console.log("Created by 0x");

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>ZeroX Labs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        Hello world
      </div>
    </div>
  )
}
